# this is renamed and stored in /etc/gitcache/config.toml

sync_interval = 10 # Interval in seconds to check for updates
enable_status_server = true # Enable the status server
status_server_port = 8080 # Port to serve the status server on
use_bootstrap = false # use bootstrap based template for status server

[[repos]]
cache_path = "./data/repo1"  # Path to your local cached repo
remote_url = "https://gitea.server.local/git/mygroup/repo1.git"  # Replace with actual remote URL
branch = "main"  # Change to the branch you want to track
# desc = "My 1st Repo" # OPTIONAL - Add a description which is displeyed in the logs
# force_clone = true # OPTIONAL - Force clone the repo on start, even if it exists

[[repos]]
cache_path = "./data/repo2"  # Path to your local cached repo
remote_url = "https://github.com.local/git/mygithubacct/repo2.git"  # Replace with actual remote URL
branch = "dev"  # Change to the branch you want to track
